-- Seed the shared drill library (96 drills), in batches of 12.
-- Run once in the Supabase SQL Editor, after schema.sql.
-- Safe to re-run: skips any drill whose name already exists.
-- If one batch errors, the earlier batches that already ran are unaffected —
-- fix the issue and re-run just this file again (it's idempotent).

-- Batch 1/8 (drills 1-12)
insert into public.drills (name, category, difficulty, description, tags, duration, participants, equipment)
select * from (values
  ('Dynamic Stretch & Movement Circuit', 'Warm-up', 'Beginner', 'Players move through a series of dynamic stretches (high knees, butt kicks, carioca, lunges) across the court to raise heart rate and prepare joints for play.', '{"dynamic stretching","mobility","pre-practice","injury prevention"}'::text[], 10, 'Full team', 'None'),
  ('Pepper Warm-up', 'Warm-up', 'Beginner', 'Partners pass, set, and hit a ball back and forth in a controlled pattern to warm up passing platforms, hands, and arm swings.', '{"pepper","partner drill","ball control","pre-practice"}'::text[], 10, 'Pairs', '1 ball per pair'),
  ('Mirror Drill', 'Warm-up', 'Beginner', 'Partners stand a few feet apart facing each other. One partner is the "leader" and makes quick, random movements (lateral shuffles, arm waves, squats, reaches) while the other mirrors them as closely and quickly as possible. Switch leader/follower roles halfway through. Builds reaction time, focus, and court awareness while raising heart rate.', '{"warm-up","reaction","partner drill","agility","team building"}'::text[], 5, 'Pairs', 'None'),
  ('Serve and Run', 'Warm-up', 'Beginner', 'Place a server on each side of the net. Each server serves five balls, trying to land them accurately, then immediately jogs around the net to the other side to join that line and take a turn from there. Combines light serving reps with continuous movement to raise heart rate before practice.', '{"warm-up","serve","conditioning","continuous movement"}'::text[], 8, 'Full team split across both sides', 'Cart of balls, net'),
  ('Butterfly Toss Warm-up', 'Warm-up', 'Beginner', 'In pairs or small groups, a coach or partner tosses easy, predictable balls for players to pass, set, or catch, cycling quickly through the group. Used as the first few minutes of practice to get hands and platforms moving before adding any pressure or competition.', '{"warm-up","passing","ball handling","fundamentals"}'::text[], 5, 'Pairs or small groups', '1 ball per group'),
  ('Footwork & Agility Warm-up Circuit', 'Warm-up', 'Beginner', 'Players move down the court through a sequence of volleyball-specific footwork patterns — defensive shuffle, sumo shuffle (wide-stance lateral steps with arm swings), and speed-skater hops — before finishing with a few high skips to prime the legs for approach jumps. Performed as a continuous circuit rather than static stretching.', '{"warm-up","footwork","agility","mobility","pre-practice"}'::text[], 8, 'Full team', 'None'),
  ('Target Serving', 'Serving', 'Intermediate', 'Servers aim for cones or hoops placed in the deep corners, short zones, and seams of the opposing court, scoring points for hitting targets to build serve accuracy.', '{"serve accuracy","target practice","float serve","jump serve"}'::text[], 15, 'Individual, rotating queue', 'Cones or hoops, cart of balls'),
  ('Serve & Move', 'Serving', 'Intermediate', 'Players serve from behind the endline and immediately sprint to a designated defensive position, simulating the transition from serving to playing defense.', '{"serve","transition","conditioning","game-like"}'::text[], 12, 'Full team', 'Cart of balls'),
  ('Dead Fish', 'Serving', 'Beginner', 'Split players into two teams of servers on opposite sides of the net. Everyone serves at the same time. As soon as someone misses, they must go sit on the other side of the court until one of their teammates serves a ball that the player can catch. Once you catch a ball, you return to the game. Time the drill for 5-10 minutes, and whichever team has the most "live fish" wins.', '{"serve","game-like","team game","competitive","elimination"}'::text[], 10, '8+ players', 'Cart of balls, net'),
  ('Serve 5', 'Serving', 'Intermediate', 'Five different servers each serve five balls at three receivers. Each server records the pass outcome for her own serves on a whiteboard (0, 1, 2, or 3); each receiver records her own pass outcomes the same way. A serve hit out of bounds counts as 4 points against the server. The server with the lowest total wins for servers; the passer with the highest total wins for passers.', '{"serve","serve receive","scoring","competitive","accountability"}'::text[], 15, '5 servers + 3 receivers', 'Cart of balls, whiteboard'),
  ('21 Down', 'Serving', 'Intermediate', 'Divide players into two teams, one on each side of the net. Each team keeps three passers in standard serve-receive position across the width of the court; everyone else lines up behind the endline as servers. Play begins with one side serving to the other''s passers; after passing, a passer switches out with a server coming in from the back line. The two sides then alternate serving back and forth. Each team starts at 21 points. Score off the receiving team''s pass quality: a 3-pass (perfect) subtracts 0, a 2-pass subtracts 1, a 1-pass subtracts 2, and a 0-pass (ace) subtracts 3. If the serving team misses their serve, the receiving team gains a point instead. The game ends when a team''s score reaches zero.', '{"serve","serve receive","passing","competitive","scoring","game-like"}'::text[], 20, '12+ players (two teams of 3 passers + servers)', 'Cart of balls, net'),
  ('Sideline Lane', 'Serving', 'Advanced', 'Two teams on opposite sides of the net. Mark off a target lane running down the sideline, extending about 12 feet in from the endline. The first team to land five serves inside the marked lane wins.', '{"serve","serve accuracy","target practice","competitive"}'::text[], 15, 'Two teams', 'Cart of balls, tape or cones to mark the lane')
) as v(name, category, difficulty, description, tags, duration, participants, equipment)
where not exists (
  select 1 from public.drills d where d.name = v.name
);

-- Batch 2/8 (drills 13-24)
insert into public.drills (name, category, difficulty, description, tags, duration, participants, equipment)
select * from (values
  ('Rotation Serving', 'Serving', 'Intermediate', 'Two teams on opposite sides of the net serve at their own pace. One team sends a player to sit in zone 1 on the opposing court; a teammate must successfully serve a ball that the zone-sitting player can catch. Once caught, that player returns to their team''s serving line, and the player who made the successful serve goes to sit in zone 2 next. Play continues zone by zone. The team must cycle a player through all six zones twice to win.', '{"serve","target practice","zones","team game","competitive"}'::text[], 20, 'Two full teams', 'Cart of balls, net'),
  ('Infiltrate', 'Serving', 'Beginner', 'Divide players into two teams on opposite sides of the net. Players serve across the net; if a player''s serve is in, she runs to the other side and joins the opponent''s serving line. Once on the opponent''s side, she stays there regardless of whether her future serves land in or out. The first team to get everybody onto the other side wins. Players shag their own ball after each serve and get back in line. Strategy note: a player who has infiltrated the opposing line should serve, shag, and get back in that line quickly to prevent the opposing team from serving consecutively, which prolongs their own team''s path to victory.', '{"serve","serve accuracy","team game","competitive","game-like"}'::text[], 15, 'Two full teams', 'Cart of balls, net'),
  ('Toss and Drop', 'Serving', 'Beginner', 'Working individually near the service line, players toss the ball in front of their hitting shoulder and let it drop naturally to the floor without swinging, about an arm''s length ahead of them. Repeating this trains a steady, repeatable toss — the foundation of a consistent serve.', '{"serve","toss","technique","fundamentals","individual"}'::text[], 5, 'Individual', '1 ball per player'),
  ('Serving Challenge', 'Serving', 'Beginner', 'Partners face off across the net, one serving while the other catches. The server''s goal is 10 clean, catchable serves in a row; a miss or an uncatchable serve resets the count to zero. Switch roles once a partner hits the target.', '{"serve","serve accuracy","partner drill","consistency"}'::text[], 10, 'Pairs', '1 ball per pair'),
  ('Serving Around the World', 'Serving', 'Intermediate', 'Mark the court into its six standard zones. Servers must land a serve in each zone in order, 1 through 6, before moving to the next zone — a missed or misplaced serve doesn''t advance them. First server (or team) to complete all six zones wins.', '{"serve","serve accuracy","target practice","zones","competitive"}'::text[], 12, 'Individual or small groups, rotating queue', 'Cart of balls, cones or tape to mark zones'),
  ('Sprint and Serve', 'Serving', 'Intermediate', 'Combines conditioning with serve accuracy. Players serve to each of the six court zones (right back, right front, middle front, left front, left back, middle back) in sequence. After every serve, the player sprints to the other side to retrieve their ball and sprints back to the service line before their next attempt.', '{"serve","conditioning","serve accuracy","zones","endurance"}'::text[], 12, 'Full team, rotating queue', 'Cart of balls, cones to mark the 6 zones'),
  ('Field Goal', 'Serving', 'Advanced', 'Set up a narrow target zone using antennas or standing markers, similar to a field-goal post, somewhere in the serving zone. Players must serve the ball between the markers to score. As players improve, narrow the gap between the markers to keep raising the accuracy demand.', '{"serve","serve accuracy","target practice","progression"}'::text[], 12, 'Individual, rotating queue', 'Cart of balls, antennas or standing markers'),
  ('Big Point', 'Serving', 'Advanced', 'Simulates high-pressure, game-deciding moments. The coach calls out a live match scenario (e.g. "championship point, you''re serving") before each rep, and the server has to execute under the weight of a single simulated serve that decides the outcome. Track makes vs. misses to reinforce accountability under pressure.', '{"serve","pressure","game-like","mental training"}'::text[], 10, 'Full team, one server at a time', 'Cart of balls, scoreboard (optional)'),
  ('Serve and Set', 'Serving', 'Intermediate', 'Combines serving with an immediate offensive transition. After serving, the server (or a teammate) becomes part of the next play — receiving a return pass and setting it to a hitter — so players practice turning a serve directly into a scoring opportunity rather than treating it as an isolated skill.', '{"serve","setting","transition","game-like"}'::text[], 12, 'Server + setter + 1-2 hitters', 'Cart of balls, net'),
  ('The Wave', 'Serving', 'Intermediate', 'Two full teams of three play a serve-receive formation on each side of the net at once. Servers may not serve the same court spot or target the same receiver twice in a row (penalty: burpees or pushups if they do). The receiving team''s goal is 10 good passes to target as a group; any overpass or ball on the floor resets their count to zero. After every three good passes, receivers rotate one spot over (left to right, right to middle, etc.) so everyone plays every position. Run for 2-minute rounds — a team that doesn''t reach 10 good passes in the round runs a quick conditioning consequence.', '{"serve","serve receive","passing","competitive","rotation","game-like"}'::text[], 10, 'Two teams of 3+ (servers and receivers)', 'Net, cart of balls'),
  ('Serve Receive Progression', 'Passing & Receiving', 'Intermediate', 'Coaches or tossers feed serves from behind the endline to passers stationed in a receive formation; passers try to deliver a quality pass to the target zone near the setter.', '{"serve receive","passing","platform","target zone"}'::text[], 15, '6-8 players + tosser', 'Cart of balls, target cone'),
  ('Wall Passing', 'Passing & Receiving', 'Beginner', 'Players pass a ball repeatedly against a wall, focusing on platform angle and consistent contact to build passing touch.', '{"passing","platform","individual","fundamentals"}'::text[], 8, 'Individual', 'Wall, 1 ball per player')
) as v(name, category, difficulty, description, tags, duration, participants, equipment)
where not exists (
  select 1 from public.drills d where d.name = v.name
);

-- Batch 3/8 (drills 25-36)
insert into public.drills (name, category, difficulty, description, tags, duration, participants, equipment)
select * from (values
  ('Queen of the Court Passing', 'Passing & Receiving', 'Intermediate', 'Three passers compete to make the cleanest passes off coach-initiated serves or hits; the best passer stays on the court while others rotate through, adding competitive pressure to receiving reps.', '{"passing","competitive","serve receive","pressure"}'::text[], 15, 'Groups of 3-4', 'Cart of balls'),
  ('Servers vs. Passers', 'Passing & Receiving', 'Intermediate', 'Three passers set up in positions 1, 6, and 5 on one side of the net, with a target player standing in the setter''s spot (position 2). Everyone else lines up on the other side as servers, serving one at a time. Passers earn a point for each pass that reaches the target; servers earn a point for each ace or unplayable serve — encouraging aggressive serving and disciplined passing at the same time.', '{"serve receive","passing","target","competitive"}'::text[], 15, '3 passers + target + rotating servers', 'Cart of balls, net'),
  ('Zone Movement Passing', 'Passing & Receiving', 'Beginner', 'A coach tosses balls one at a time to different zones around a passer — short, deep, left, right. The passer must shuffle into position before contact rather than reaching or leaning, then deliver the pass back toward a target at center court. Emphasizes moving to the ball first and passing second.', '{"passing","footwork","movement","fundamentals"}'::text[], 8, '1 passer + 1 coach/tosser, rotating', 'Cart of balls'),
  ('Passing Shuttle', 'Passing & Receiving', 'Intermediate', 'A player passes a tossed ball to a target, then immediately sprints to a new spot on the court to receive the next toss. Repeating this at pace mimics the constant repositioning of live play and builds reaction time and passing quality under mild fatigue.', '{"passing","agility","conditioning","game-like"}'::text[], 10, '1 passer + 1 tosser, rotating', 'Cart of balls'),
  ('Tug-of-War', 'Passing & Receiving', 'Intermediate', 'Split the group into servers and passers. Start a shared score at 5. A good pass adds a point for the passers; a bad pass subtracts one. A missed serve also adds a point for the passers. Passers win if the score reaches 10; servers win if it drops to 0. Swap roles and play again.', '{"passing","serve receive","scoring","competitive"}'::text[], 12, 'Two groups (servers vs. passers)', 'Cart of balls, net, whiteboard for score (optional)'),
  ('Serve-Receive Ladder', 'Passing & Receiving', 'Advanced', 'Split the court in half to run several simultaneous mini-games as "ladder" courts. Each group of three rotates through server, passer, and target roles. After a fixed number of serves (e.g. 10) or a set time, the group with the best passing results moves up a court and the weaker group moves down; the middle group stays. Ties go to whichever group started higher on the ladder.', '{"serve receive","passing","competitive","tournament"}'::text[], 20, 'Multiple groups of 3+', 'Cart of balls per court'),
  ('Six-Out Rotation', 'Passing & Receiving', 'Advanced', 'The full team lines up in all six rotations. The team must earn a clean, successful serve-receive (one that leads to a simulated point) in each rotation, in order, before advancing to the next — a shaky pass keeps them in that rotation until they get it right. Using match-speed serves tests both individual passing and full-team organization and communication.', '{"serve receive","passing","rotation","team","game-like"}'::text[], 20, 'Full team (6+)', 'Cart of balls, net'),
  ('Stay Low Passing', 'Passing & Receiving', 'Beginner', 'Partners start on opposite sidelines on opposite sides of the net. Staying in a low, athletic stance the whole time, they shuffle laterally along the net in sync while passing the ball continuously back and forth to each other over the net. Keeping the platform low and moving builds the leg strength and habit of passing from a stable base instead of standing tall and reaching.', '{"passing","footwork","technique","partner drill","fundamentals"}'::text[], 8, 'Pairs', '1 ball per pair, net'),
  ('Setter Footwork Ladder', 'Setting', 'Intermediate', 'Setters work through footwork patterns (shuffle, crossover, sprint) to the target area using an agility ladder, then finish each rep by setting a tossed ball.', '{"setter","footwork","agility","fundamentals"}'::text[], 10, 'Setters', 'Agility ladder, balls'),
  ('Three-Person Setting Triangle', 'Setting', 'Beginner', 'Three players form a triangle and set the ball around continuously, emphasizing hand shape, footwork to the ball, and consistent set height and location.', '{"setting","hand shape","partner drill","fundamentals"}'::text[], 10, 'Groups of 3', '1 ball per group'),
  ('Setter Tempo Sets', 'Setting', 'Advanced', 'A tosser feeds balls to the setter from various positions on the court; the setter delivers quick sets (1s, 2s, back sets) to hitters at different tempos to develop touch and decision-making.', '{"setter","tempo","quick set","decision making"}'::text[], 15, 'Setter + 3-4 hitters', 'Cart of balls'),
  ('Wall Setting', 'Setting', 'Beginner', 'Standing several feet from a wall, the setter sets the ball against it repeatedly, trying to hit the same spot every time and keeping the ball on a consistent, controlled path back to their hands. A simple, equipment-light way to groove clean hand shape and touch without needing a partner.', '{"setting","technique","individual","fundamentals"}'::text[], 8, 'Individual', 'Wall, 1 ball')
) as v(name, category, difficulty, description, tags, duration, participants, equipment)
where not exists (
  select 1 from public.drills d where d.name = v.name
);

-- Batch 4/8 (drills 37-48)
insert into public.drills (name, category, difficulty, description, tags, duration, participants, equipment)
select * from (values
  ('Setting to Different Angles', 'Setting', 'Intermediate', 'A coach tosses balls to a variety of spots around the setter — short, deep, off to either side — instead of feeding a predictable, in-system ball. The setter has to adjust footwork quickly on each rep and still deliver an accurate set to target, building comfort with imperfect first contact.', '{"setting","footwork","adaptability","accuracy"}'::text[], 10, 'Setter + coach/tosser', 'Cart of balls'),
  ('Progressive Ball Drops', 'Setting', 'Intermediate', 'Three back-row players stand at right, middle, and left positions with the setter in the center of the court. Each back-row player, in turn, drops or passes the ball to a spot progressively closer to (or farther from) the setter''s base position, forcing the setter to adjust footwork on the fly and still deliver a clean, accurate set.', '{"setting","footwork","adaptability","fundamentals"}'::text[], 10, '4 players', 'Cart of balls'),
  ('Three Touches Drill', 'Setting', 'Advanced', 'Two setters face the net. On the first touch, the setter takes a slanted angle toward the ball; on the second touch, she squares her body fully to the net; on the third touch, she pushes the set forward or backward to a target hitter. Running the sequence repeatedly grooves the footwork and body positioning that turns a scrambled first contact into a clean, usable set.', '{"setting","footwork","technique","decision making"}'::text[], 12, '2+ setters', 'Cart of balls, net'),
  ('Back Row to Front/Back Attack', 'Setting', 'Advanced', 'The setter starts in the back row and receives a pass or toss from a coach or teammate, then delivers a set to either a front-row or back-row hitter based on a call or read. Immediately after setting, she sprints to the net to cover the hit in case it''s blocked back. Trains the full sequence a back-row setter runs during a real rally.', '{"setting","back row","transition","game-like"}'::text[], 12, '3+ players', 'Cart of balls, net'),
  ('Set and Go', 'Setting', 'Advanced', 'Four setters position around the net — two on the pins, two split between pin and center — each facing across the court. The ball moves in a continuous pin-to-pin pattern (center sets to one pin, that pin sets long to the far pin, which sets to the other mid-court setter, who sets back to center) while extra players rotate between running the court perimeter and holding a core exercise. After every set, the setter sprints to the next open position in the rotation. Combines high-rep setting with conditioning.', '{"setting","conditioning","footwork","fast-paced"}'::text[], 12, '6+ players', '1 ball'),
  ('Line & Cross-Court Hitting', 'Attacking', 'Intermediate', 'Hitters take approach swings against a tossed or set ball, alternating between hitting down the line and cross-court to develop shot placement and shoulder control.', '{"hitting","attacking","shot placement","approach"}'::text[], 15, 'Hitters + setter/tosser', 'Cart of balls'),
  ('Approach & Armswing Progression', 'Attacking', 'Beginner', 'Players break down the attack approach into steps (rhythm, plant, jump, armswing) starting slow and without a ball, then progress to full-speed approaches finishing with a hit off a toss.', '{"hitting","approach","armswing","fundamentals"}'::text[], 12, 'Hitters', 'Cart of balls'),
  ('Hitting Off the Block', 'Attacking', 'Advanced', 'Hitters attack against a single or double block, practicing shots that go around, off, or through the block, including tools, wipes, and cut shots.', '{"hitting","blocking","shot selection","game-like"}'::text[], 15, 'Hitters + blockers + setter', 'Cart of balls'),
  ('Wall Approach Swing', 'Attacking', 'Beginner', 'Facing a wall with no ball in play, players run their full attack approach and arm swing, focusing on the bow-and-arrow arm position (hitting arm back, opposite arm up) before snapping through an imaginary contact point. Isolating the mechanics away from a live set makes it easy for beginners to groove proper arm-swing technique before adding the pressure of hitting off a real toss.', '{"hitting","approach","armswing","fundamentals","technique"}'::text[], 8, 'Individual', 'Wall, open space'),
  ('Target Practice Drill', 'Attacking', 'Intermediate', 'Mark target zones on the floor with tape, cones, or mats in specific areas of the court (down the line, cross-court, deep corner). A server-passer-setter sequence feeds a rotating attacker, who tries to place a hard spike or well-controlled shot into the marked target. Turn it into a competition where the first attacker to 5 or 10 target hits wins.', '{"hitting","target practice","shot placement","competitive"}'::text[], 15, '3+ players (server, setter, rotating attackers)', 'Cart of balls, net, tape/cones/mats for targets'),
  ('Seated Box Spike', 'Attacking', 'Intermediate', 'Players start seated on a box angled roughly like their legs would be mid-approach. A coach tosses the ball in front of them; the player punches their feet into the ground and jumps explosively to attack it. Removing the running approach lets hitters isolate a fast, powerful takeoff with minimal ground contact time.', '{"hitting","approach","power","takeoff","technique"}'::text[], 10, 'Hitters + coach/tosser', 'Box or bench, cart of balls'),
  ('Fish-Eye Vision', 'Attacking', 'Advanced', 'A setter feeds a hitter at the net. Right before contact, the hitter uses peripheral vision to read the blockers and defense on the opposite court while keeping her eyes and shoulders square to the set, then intentionally hits into the net instead of over it so the rep can repeat quickly without shagging balls. Builds the habit of reading the defense without turning the head.', '{"hitting","vision","reading defense","decision making"}'::text[], 10, 'Hitter + setter', 'Cart of balls, net')
) as v(name, category, difficulty, description, tags, duration, participants, equipment)
where not exists (
  select 1 from public.drills d where d.name = v.name
);

-- Batch 5/8 (drills 49-60)
insert into public.drills (name, category, difficulty, description, tags, duration, participants, equipment)
select * from (values
  ('Sideline Alley Hitting', 'Attacking', 'Advanced', 'Mark two-foot alleys running down both sidelines. Outside hitters line up single-file while a coach hits or tosses to a defender, who digs to a setter. After setting, the setter calls out a direction (left or right), and the hitter must spike the ball into that sideline''s alley to score, practicing shot placement under a late decision call.', '{"hitting","shot placement","decision making","game-like"}'::text[], 15, 'Coach + defender + setter + rotating hitters', 'Cart of balls, net, tape or cones to mark alleys'),
  ('Back Row Attack Progression', 'Attacking', 'Advanced', 'A backcourt group (2-3 passers, a setter, and an attacker) defends a live serve from the other side of the net. The setter delivers a back-row set to the attacker, who must jump from behind the attack line to spike it for a kill. Play continues live if the attack is dug, giving back-row hitters game-realistic reps under pressure.', '{"hitting","back row attack","transition","game-like"}'::text[], 15, '6+ players', 'Cart of balls, net'),
  ('Tool Shot Training', 'Attacking', 'Advanced', 'Hitters intentionally attack off a blocker''s hands (a "tool" or "wipe") to controlled zones down the sideline or in the deep corner, rather than trying to hit around or through the block. Track successful tool shots and require the attacking team to be ready to transition immediately, since a tooled ball often comes right back into play off the block.', '{"hitting","tool shot","blocking","shot selection"}'::text[], 15, 'Hitters + blockers + setter', 'Cart of balls, net'),
  ('Mix It Up', 'Attacking', 'Advanced', 'A five-part progressive team drill. In three 5-minute controlled segments, one lineup hits against a set defense using only one shot type per segment: tips only, then chip/roll shots only, then full swings only. A short freeball warm-up phase lets either side use any shot. In the final competitive phase (live free-ball/down-ball play), a team must record one kill from a tip, one from a chip/roll shot, and one from a full swing before those three "little points" convert into one "big point" — first team to three big points wins. Forces hitters to vary their attacks instead of relying on one shot.', '{"hitting","shot selection","shot variety","competitive","game-like"}'::text[], 25, 'Two full lineups', 'Cart of balls, net'),
  ('Block Footwork & Hand Position', 'Blocking', 'Beginner', 'Blockers practice lateral shuffle and crossover steps along the net, closing to a designated spot and finishing with a controlled jump and proper hand penetration over an imaginary net line.', '{"blocking","footwork","fundamentals","net play"}'::text[], 10, 'Front row players', 'Net'),
  ('Read & React Blocking', 'Blocking', 'Advanced', 'A coach or setter sets to different hitters while blockers read the set location and hitter approach, practicing timing their jump to close the block.', '{"blocking","reading","timing","game-like"}'::text[], 15, 'Blockers + setter + hitters', 'Cart of balls, net'),
  ('Coach-on-a-Box', 'Blocking', 'Beginner', 'A coach stands on a box near the net, holding a ball at a fixed height above the tape. The blocker times a straight-up jump and presses both hands over the net toward the ball. Repeating this at a controlled, predictable height helps beginners groove timing, eye tracking, and proper arm extension before adding a live hitter.', '{"blocking","technique","timing","fundamentals"}'::text[], 8, 'Blocker + coach', 'Box, 1 ball, net'),
  ('Toss-and-Block', 'Blocking', 'Beginner', 'A partner or coach on the other side of the net tosses the ball up near the net. The blocker reads the toss and times a jump to make contact with it at its peak, simulating blocking a live attack without the speed and unpredictability of a real swing yet.', '{"blocking","timing","reaction","fundamentals"}'::text[], 8, 'Pairs', '1 ball, net'),
  ('Block and Run', 'Blocking', 'Intermediate', 'A blocker sets up and blocks at one position along the net, then immediately shuffles or sprints down the net to a second position and blocks again, repeating down the line. Builds the lateral quickness and repeat-effort needed to close multiple blocks in a single rally.', '{"blocking","footwork","agility","conditioning"}'::text[], 10, 'Individual or small group, rotating', 'Net, cart of balls'),
  ('Matrix Blocking', 'Blocking', 'Advanced', 'The coach pre-assigns which zone the attack will go to before the play starts. Blockers must read the setter''s cues (set location, tempo) and get into position before the hitter jumps, then execute the block on the called zone. Builds recognition of common offensive patterns rather than pure reaction.', '{"blocking","reading offense","decision making"}'::text[], 15, 'Blockers + setter + hitter', 'Cart of balls, net'),
  ('Blind Blocking', 'Blocking', 'Advanced', 'The blocker doesn''t know in advance where the set is going. She has to read the setter''s body language and hand position along with the hitter''s approach to decide where and when to jump, with no predictable cue from the coach. Sharpens pure read-and-react instinct for game situations where nothing is scripted.', '{"blocking","reading offense","instinct"}'::text[], 15, 'Blockers + setter + hitter', 'Cart of balls, net'),
  ('Four-Blocker Peel', 'Blocking', 'Advanced', 'Four blockers form two lines across the net. After each rep, the outside player in each line "peels" off to the back of the line while the inside player practices the crossover step to fill the vacated spot. Cycling through builds multi-blocker coordination and clean footwork for both outside and middle blockers.', '{"blocking","footwork","team coordination"}'::text[], 12, '4 blockers', 'Cart of balls, net')
) as v(name, category, difficulty, description, tags, duration, participants, equipment)
where not exists (
  select 1 from public.drills d where d.name = v.name
);

-- Batch 6/8 (drills 61-72)
insert into public.drills (name, category, difficulty, description, tags, duration, participants, equipment)
select * from (values
  ('Dig & Transition to Attack', 'Defense & Digging', 'Advanced', 'Defenders dig a hard-driven ball hit or thrown by the coach, then the team transitions immediately into an attack, emphasizing quick recovery from defense to offense.', '{"digging","defense","transition","game-like"}'::text[], 15, '6 players', 'Cart of balls'),
  ('Sprawl & Roll Recovery', 'Defense & Digging', 'Intermediate', 'Players practice diving, sprawling, and rolling techniques to recover balls hit just out of reach, focusing on safe landing mechanics and quick return to a ready position.', '{"digging","diving","technique","fundamentals"}'::text[], 10, 'Full team', 'Mats (optional)'),
  ('Emergency Defense Circle', 'Defense & Digging', 'Intermediate', 'Players stand in a circle and the coach hits or tosses balls unpredictably at each player, forcing quick emergency-style digs and reflex reactions.', '{"digging","reaction","reflex","fundamentals"}'::text[], 8, 'Group of 6-8', 'Cart of balls'),
  ('Angle Digging', 'Defense & Digging', 'Beginner', 'A coach or player tosses or hits balls at varying angles from the net, forcing the defender to read the trajectory and move laterally to get a platform under the ball. Keeping the tosses varied (but not yet full-speed swings) builds the footwork and angle-reading defenders need before facing live hitters.', '{"digging","defense","footwork","angles","fundamentals"}'::text[], 8, 'Defender + coach/tosser', 'Cart of balls'),
  ('Coach-on-Box Digging', 'Defense & Digging', 'Intermediate', 'Three defenders set up in left-back, middle-back, and right-back with a target player in the setter position. A coach stands on a box at the net and attacks unpredictably — hard swings, roll shots, and tips — at each defender in turn. Each dig is scored on a 3-2-1 scale (3 = settable, 2 = playable, 1 = kept off the floor). Run 15 balls per trio, then rotate in a new group.', '{"digging","defense","reaction","scoring"}'::text[], 12, '3 defenders + coach + scorer', 'Box, cart of balls, target marker'),
  ('Dig and Replace', 'Defense & Digging', 'Advanced', 'A line of defenders forms behind the middle-back position while a coach attacks from a box at the net. After digging, a defender immediately sprints off to the sideline while the next player in line fills the vacated spot within about two seconds; any shanked ball must be chased down rather than left to roll. Keeps reps continuous and trains the transition in and out of the defensive position under fatigue.', '{"digging","defense","transition","conditioning"}'::text[], 10, '4+ defenders, rotating', 'Box, cart of balls, target marker'),
  ('Tip and Roll Coverage', 'Defense & Digging', 'Advanced', 'Three defenders line up behind a coach on a box and a blocker at the net. The coach shows a full attacking swing on every rep but mixes in hard-driven attacks with tips and roll shots. Defenders must hold their base position until contact is actually made, then release toward the ball — a tip or roll that hits the floor counts against the group on the 3-2-1 scoring chart.', '{"digging","defense","tips","reading","scoring"}'::text[], 12, '3 defenders + coach + blocker', 'Box, cart of balls, target marker'),
  ('Pursuit', 'Defense & Digging', 'Advanced', 'Six defenders spread across the court while a coach, standing anywhere behind them with a cart of balls, hits or tosses to deliberately awkward, hard-to-reach spots. The nearest player must pursue and keep the ball alive; the team needs three clean contacts to send it back over the net to score a point. Play to 7 points or a 6-minute time cap, whichever comes first.', '{"digging","defense","pursuit","competitive","conditioning"}'::text[], 10, '6 defenders + coach', 'Cart of balls, net'),
  ('Team Defense Wash', 'Defense & Digging', 'Advanced', 'A full six-player defense faces a coach running a live-ish offense with two hitters. The defending team must earn three clean digs-to-target before the attacking side records five kills. Whichever side loses the "wash" takes over as the attacking side for the next round, keeping both sides accountable.', '{"digging","defense","competitive","game-like","team"}'::text[], 15, '6 defenders + coach + 2 hitters', 'Cart of balls, net'),
  ('Four-Corner Ball Control', 'Ball Control', 'Beginner', 'Players rotate through four stations at the corners of the court, passing, setting, and hitting a continuously moving ball to build all-around touch under mild fatigue.', '{"ball control","rotation","fundamentals","endurance"}'::text[], 12, '8-12 players', '2-3 balls'),
  ('Partner Pepper', 'Ball Control', 'Beginner', 'Two players continuously hit, pass, and set a ball back and forth over a short distance, keeping the rally alive to build touch, communication, and control.', '{"pepper","ball control","partner drill","fundamentals"}'::text[], 10, 'Pairs', '1 ball per pair'),
  ('Triangle Control', 'Ball Control', 'Beginner', 'Three players form a triangle and keep the ball alive using any combination of passes, sets, and controlled hits within the triangle, without letting it touch the floor. Track the longest rally the group can string together and try to beat that number each round.', '{"ball control","teamwork","fundamentals","rally"}'::text[], 10, 'Groups of 3', '1 ball per group')
) as v(name, category, difficulty, description, tags, duration, participants, equipment)
where not exists (
  select 1 from public.drills d where d.name = v.name
);

-- Batch 7/8 (drills 73-84)
insert into public.drills (name, category, difficulty, description, tags, duration, participants, equipment)
select * from (values
  ('24 Consecutive Touches', 'Ball Control', 'Beginner', 'The full team works together to keep one ball alive using passes, sets, and controlled hits, with the goal of reaching 24 consecutive touches without the ball hitting the floor or going out of bounds. Every player should get involved rather than a few players hogging the ball. Restart the count from zero on any drop.', '{"ball control","team","communication","cooperative"}'::text[], 10, 'Full team', '1 ball'),
  ('Rapid Fire Passing', 'Ball Control', 'Intermediate', 'One passer stands in the middle while two or more tossers surround her from different directions and angles, feeding balls one after another with minimal pause. The passer has to move, adjust, and control each ball to a target without losing her base. Run in 20-30 second bursts, then rotate the passer.', '{"ball control","passing","reaction","footwork"}'::text[], 10, '1 passer + 2+ feeders, rotating', 'Cart of balls'),
  ('Pass and Jump Set Progression', 'Ball Control', 'Intermediate', 'Starting from a toss or easy serve, a player passes the ball to a target area, then quickly transitions into the setter position and finishes with a jump set to a specific target. Combines two touches into one continuous sequence to build the footwork and control needed to go straight from passing into setting.', '{"ball control","setting","footwork","transition"}'::text[], 10, '1+ (add a hitter once comfortable)', 'Cart of balls'),
  ('Musical Volleyball', 'Ball Control', 'Intermediate', 'Split the team into two even sides of at least four players. Play alternates between a cooperative phase (music on) where both sides just try to keep the ball alive and control it cleanly, and a competitive phase (music off) where the same rally suddenly becomes a real point-scoring rally. Both sides start at 15 points; cooperative errors (drops, out of bounds) cost a point, while competitive rallies are scored normally. First team to 25 wins. A whistle works fine instead of music if there''s no speaker.', '{"ball control","team game","competitive","fun","cooperative"}'::text[], 15, 'Two teams of 4+', 'Net, cart of balls, music/speaker or whistle'),
  ('Reaction Digs', 'Ball Control', 'Advanced', 'A player starts from an awkward position — sitting, kneeling, or turned away from the net — while a partner sends a ball at them with little warning. The player has to react immediately, get a platform under the ball, and control it back to a usable target. Builds the scrambling ball control needed for balls that arrive when a player isn''t in a normal ready stance.', '{"ball control","reaction","digging"}'::text[], 8, 'Pairs', '1 ball per pair'),
  ('Suicide Sprints with Ball Touch', 'Conditioning', 'Beginner', 'Players sprint to progressively farther lines on the court, touching the floor at each line, then finish with a defensive shuffle and a controlled ball contact.', '{"conditioning","sprints","endurance","footwork"}'::text[], 8, 'Full team', '1 ball'),
  ('Court Sprints & Jump Series', 'Conditioning', 'Intermediate', 'A circuit combining baseline-to-baseline sprints, lateral shuffles, and vertical jump repetitions to build the explosive power and stamina volleyball demands.', '{"conditioning","jumping","power","endurance"}'::text[], 10, 'Full team', 'None'),
  ('Agility Ladder Footwork', 'Conditioning', 'Beginner', 'Using an agility ladder laid flat on the floor, players move through it with different footwork patterns — two-feet-in-each-box, lateral scissor steps, in-in-out-out — focusing on quick, precise foot placement rather than speed at first. Builds the foot speed and coordination that carries over into defensive shuffles and approach footwork.', '{"conditioning","agility","footwork","coordination"}'::text[], 8, 'Individual, rotating', 'Agility ladder'),
  ('Core Stability Circuit', 'Conditioning', 'Beginner', 'Players rotate through a short circuit of core-focused holds — a standard forearm plank, plank with alternating leg raises, and plank "airplanes" (extending one arm forward while lifting the opposite leg out to the side) — holding each for 20-30 seconds. A strong, stable core is what lets hitters and blockers transfer leg power into the ball instead of losing it through the trunk.', '{"conditioning","core","stability","strength"}'::text[], 8, 'Full team', 'None'),
  ('T-Cone Drill', 'Conditioning', 'Intermediate', 'Set up four cones in a T shape — one at the base, one at the top-center, and one on each side of the top. From the base cone, sprint forward to the top-center cone, shuffle to the right cone, shuffle back through center to the left cone, then backpedal all the way to the start. Combines forward sprinting, lateral shuffling, and backpedaling to train quick, controlled changes of direction.', '{"conditioning","agility","footwork","change of direction"}'::text[], 10, 'Individual, rotating', '4 cones'),
  ('Lateral Hurdle Hops', 'Conditioning', 'Intermediate', 'Line up a row of low hurdles or cones. Players hop sideways over each one in quick succession, staying light and quiet on their feet, then finish the line with a maximal vertical jump. Sharpens the lateral quickness and balance blockers and defenders need to move along the net or across the back row.', '{"conditioning","agility","plyometric","footwork"}'::text[], 8, 'Individual, rotating', 'Low hurdles or cones'),
  ('Box Jump Series', 'Conditioning', 'Advanced', 'Using a sturdy box or platform, players jump onto it with both feet from a quarter-squat position, land softly with control, then step back down and reset before the next rep. Builds the explosive, fast-twitch leg power that directly carries over to attacking and blocking jump height.', '{"conditioning","plyometric","power","jumping"}'::text[], 8, 'Individual, rotating', 'Sturdy box or platform')
) as v(name, category, difficulty, description, tags, duration, participants, equipment)
where not exists (
  select 1 from public.drills d where d.name = v.name
);

-- Batch 8/8 (drills 85-96)
insert into public.drills (name, category, difficulty, description, tags, duration, participants, equipment)
select * from (values
  ('Band-Resisted Sprints', 'Conditioning', 'Advanced', 'A resistance band is looped around the sprinting player''s waist while a partner holds the other end and provides resistance. The player sprints forward for a short distance against that resistance, then walks back and resets. Builds explosive acceleration and a stronger first step for chasing down balls and closing on defense.', '{"conditioning","speed","acceleration","partner drill"}'::text[], 8, 'Pairs', 'Resistance band'),
  ('6v6 Scrimmage', 'Team & Scrimmage', 'Intermediate', 'Full live game play with regular rotations and scoring, allowing players to apply skills in a game-realistic context and giving coaches a chance to evaluate execution under pressure.', '{"scrimmage","game-like","team","live play"}'::text[], 25, '12+ players', 'Net, cart of balls, scoreboard'),
  ('Situational Scoring Games', 'Team & Scrimmage', 'Advanced', 'The coach sets up specific game situations (e.g., team down 2 points, serve receive only) and play resumes from that score, forcing players to execute under simulated match pressure.', '{"scrimmage","game-like","pressure","situational"}'::text[], 20, '12+ players', 'Net, cart of balls'),
  ('King/Queen of the Court', 'Team & Scrimmage', 'Intermediate', 'Small teams (2v2 or 3v3) play short rally-scored games on split courts; winning teams advance to the top court, creating competitive, high-intensity mini-games.', '{"scrimmage","competitive","small-sided","game-like"}'::text[], 20, '12+ players', 'Multiple nets/courts, balls'),
  ('Wash Scoring Scrimmage (7 Small, 3 Big)', 'Team & Scrimmage', 'Advanced', 'Play regular 6v6, but scoring runs on two levels. Teams rally for "small points," and a small point gets wiped out entirely (a "wash") if a defined mistake happens on the way to winning it — no call of "mine," a shanked first ball, etc. A team needs 7 clean small points to bank one "big point," which is safe from being washed; the first team to 3 big points wins the set. Raises the stakes on every single small point.', '{"scrimmage","competitive","scoring","game-like","pressure"}'::text[], 20, '12+ players', 'Net, cart of balls, scoreboard'),
  ('Virginia Math', 'Team & Scrimmage', 'Intermediate', 'Play live 6v6, but instead of one point per rally, whichever team wins the rally scores a point for every time the ball crossed the net during that rally. A short 3-touch-and-over rally is worth little; a long, drawn-out exchange is worth a lot. Rewards teams for extending points and punishes unforced errors that end a rally early.', '{"scrimmage","scoring","game-like","competitive"}'::text[], 20, '12+ players', 'Net, cart of balls, scoreboard'),
  ('Steal the Ball', 'Team & Scrimmage', 'Advanced', 'Start with an even pile of extra balls split between both sides. Play live rally-serve; a team that wins three consecutive points "steals" one ball from the opponent''s pile and rotates. The first team to collect all of the balls wins the set. Builds sustained pressure since single points don''t matter as much as stringing together runs.', '{"scrimmage","competitive","scoring","game-like"}'::text[], 20, '12+ players', 'Net, several extra balls, scoreboard'),
  ('Kill Streaks', 'Team & Scrimmage', 'Intermediate', 'Play regular 6v6, but consecutive points won by the same team are worth escalating value — a single point is worth 1, but a team that wins three points in a row on that streak scores 3 for that point, and so on. A side-out immediately resets the streak back to 1. Rewards momentum and forces the trailing team to find any way to break the run.', '{"scrimmage","scoring","momentum","competitive","game-like"}'::text[], 20, '12+ players', 'Net, cart of balls, scoreboard'),
  ('Serve/Free/Free', 'Team & Scrimmage', 'Intermediate', 'Each sequence is a serve followed by two coach-fed free balls (down balls), for three total mini-rallies. A team that wins all three earns 2 points; a team that wins only two of the three earns 1 point. Compensates for how much dead time a normal serve creates, packing more competitive touches into the same practice time.', '{"scrimmage","scoring","serve","game-like"}'::text[], 20, '12+ players', 'Net, cart of balls, scoreboard'),
  ('Golden Ticket', 'Team & Scrimmage', 'Advanced', 'Play regular 6v6. Whenever a team accomplishes a designated tough play (e.g. a terminal block or a cover-then-win-the-rally), they''re handed a physical "golden ticket" (an old gift card works fine). At any point, the ticket holder can play it to instantly flip the current score between the two teams. If the other team wins the ticket away, it goes into a shared bank for later. Because it''s "use it or lose it," holding teams have to decide when the swing is worth the most.', '{"scrimmage","competitive","game-like","momentum"}'::text[], 20, '12+ players', 'Net, cart of balls, scoreboard, a token/ticket item'),
  ('Baseball', 'Team & Scrimmage', 'Intermediate', 'A competitive team game that simulates baseball innings. One team is "at bat" on serve-receive while the other side serves. The receiving team scores "runs" by winning rallies off the serve or a follow-up free ball, with a clean first-ball kill or an especially well-executed play worth extra runs. If the serving team wins the rally instead, or the receiving team fails to run an effective play, the batting team records an "out." After three outs, the half-inning ends and the teams switch roles. Play a set number of innings, usually 3 to 6, and total up runs to determine the winner.', '{"scrimmage","serve receive","scoring","competitive","game-like"}'::text[], 25, '12+ players', 'Net, cart of balls, scoreboard'),
  ('Collect the Balls Relay', 'Team & Scrimmage', 'Intermediate', 'Line up five balls on the sideline on each side of the net (placing them in a hula hoop or marked boundary keeps them from rolling away). A coach starts play with a free ball to one side, and that team plays the rally out live 6v6. The team that wins the rally immediately sends one player onto the court to steal a ball from the other side''s collection and carry it back to their own pile — play continues 5v6 while that player is away. As soon as the rally ends, the coach feeds in another free ball to the winning side to keep the game moving. The first team to collect all the balls on their side wins.', '{"scrimmage","competitive","game-like","team"}'::text[], 20, '12 players (6v6)', 'Net, 10 balls, 2 hula hoops or boundary markers')
) as v(name, category, difficulty, description, tags, duration, participants, equipment)
where not exists (
  select 1 from public.drills d where d.name = v.name
);
