import { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import { AutoCreateDialog } from "../components/AutoCreateDialog";
import { ConfirmDialog } from "../components/ConfirmDialog";
import { ClipboardListIcon, ClockIcon, StarIcon, WandIcon } from "../components/icons";
import { useToast } from "../components/ToastProvider";
import * as db from "../storage/db";
import type { PracticePlan } from "../types";
import { generatePlanSegments, type AutoGenerateOptions } from "../utils/autoGeneratePlan";
import { computeSchedule, formatClock, parseTimeToMinutes } from "../utils/schedule";

function drillCount(plan: PracticePlan): number {
  return plan.segments.reduce((sum, seg) => sum + (seg.kind === "drill" ? seg.tracks.length : 0), 0);
}

function timeWindowLabel(plan: PracticePlan): string | undefined {
  if (!plan.startTime || !plan.endTime) return undefined;
  const start = parseTimeToMinutes(plan.startTime);
  const end = parseTimeToMinutes(plan.endTime);
  if (start === undefined || end === undefined) return undefined;
  return `${formatClock(start)} – ${formatClock(end)}`;
}

export function Plans() {
  const [plans, setPlans] = useState<PracticePlan[]>([]);
  const [loading, setLoading] = useState(true);
  const [confirmTarget, setConfirmTarget] = useState<PracticePlan | null>(null);
  const [showAutoCreate, setShowAutoCreate] = useState(false);
  const navigate = useNavigate();
  const showToast = useToast();

  useEffect(() => {
    let active = true;
    db.getPlans().then((loaded) => {
      if (!active) return;
      setPlans(loaded);
      setLoading(false);
    });
    return () => {
      active = false;
    };
  }, []);

  async function handleAutoGenerate(options: AutoGenerateOptions) {
    const segments = generatePlanSegments(await db.getDrills(), options);
    setShowAutoCreate(false);
    if (segments.length === 0) {
      showToast("Couldn't find enough matching drills — try a longer duration or fewer filters");
      return;
    }
    navigate("/plans/new", { state: { segments, autoGenerated: true } });
  }

  async function handleDeleteConfirmed(plan: PracticePlan) {
    await db.deletePlan(plan.id);
    setPlans(await db.getPlans());
    setConfirmTarget(null);
    showToast(`"${plan.name}" deleted`);
  }

  async function handleToggleFavorite(plan: PracticePlan) {
    await db.toggleFavoritePlan(plan.id);
    setPlans(await db.getPlans());
  }

  async function handleDuplicate(plan: PracticePlan) {
    const copy = await db.addPlan({
      name: `${plan.name} (Copy)`,
      date: plan.date,
      startTime: plan.startTime,
      endTime: plan.endTime,
      notes: plan.notes,
      favorite: false,
      segments: plan.segments.map((seg) =>
        seg.kind === "break"
          ? { segmentId: db.makeId(), kind: "break", label: seg.label, duration: seg.duration }
          : {
              segmentId: db.makeId(),
              kind: "drill",
              tracks: seg.tracks.map((track) => ({ ...track, trackId: db.makeId() })),
            }
      ),
    });
    setPlans(await db.getPlans());
    showToast(`Duplicated as "${copy.name}"`);
  }

  return (
    <div className="page">
      <div className="page-header">
        <div>
          <h1>Practice Plans</h1>
          <p className="page-subtitle">{plans.length} saved plans</p>
        </div>
        <div className="page-header-actions">
          <button
            type="button"
            className="btn icon-label"
            onClick={() => setShowAutoCreate(true)}
          >
            <WandIcon /> Auto-Create Plan
          </button>
          <button type="button" className="btn btn-primary" onClick={() => navigate("/plans/new")}>
            + New Plan
          </button>
        </div>
      </div>

      {loading ? (
        <div className="empty-state">
          <p>Loading practice plans…</p>
        </div>
      ) : plans.length === 0 ? (
        <div className="empty-state">
          <ClipboardListIcon size={36} className="empty-state-icon" />
          <p>No practice plans yet. Create one and start mixing in drills from your library.</p>
        </div>
      ) : (
        <div className="plan-list">
          {plans.map((plan) => {
            const totalMinutes = computeSchedule(plan.segments).totalMinutes;
            const window = timeWindowLabel(plan);
            return (
              <div className="plan-list-item" key={plan.id}>
                <button
                  type="button"
                  className={plan.favorite ? "btn-icon fav-star fav-active" : "btn-icon fav-star"}
                  onClick={() => handleToggleFavorite(plan)}
                  aria-label={plan.favorite ? "Remove from favorites" : "Add to favorites"}
                >
                  <StarIcon />
                </button>
                <button
                  type="button"
                  className="plan-list-main"
                  onClick={() => navigate(`/plans/${plan.id}`)}
                >
                  <div className="drill-card-header">
                    <span className="drill-card-name">{plan.name}</span>
                    {plan.date && <span className="badge">{plan.date}</span>}
                  </div>
                  <div className="drill-card-meta">
                    {window && (
                      <span className="icon-label">
                        <ClockIcon /> {window}
                      </span>
                    )}
                    <span className="icon-label">
                      <ClockIcon /> {totalMinutes} min total
                    </span>
                    <span className="icon-label">
                      <ClipboardListIcon /> {plan.segments.length} blocks · {drillCount(plan)} drills
                    </span>
                  </div>
                </button>
                <button type="button" className="btn" onClick={() => handleDuplicate(plan)}>
                  Duplicate
                </button>
                <button
                  type="button"
                  className="btn btn-danger"
                  onClick={() => setConfirmTarget(plan)}
                >
                  Delete
                </button>
              </div>
            );
          })}
        </div>
      )}

      {confirmTarget && (
        <ConfirmDialog
          title="Delete practice plan?"
          message={`Delete practice plan "${confirmTarget.name}"?`}
          confirmLabel="Delete"
          danger
          onConfirm={() => handleDeleteConfirmed(confirmTarget)}
          onCancel={() => setConfirmTarget(null)}
        />
      )}

      {showAutoCreate && (
        <AutoCreateDialog onGenerate={handleAutoGenerate} onClose={() => setShowAutoCreate(false)} />
      )}
    </div>
  );
}
