import { Fragment, useEffect, useMemo, useState } from "react";
import { useLocation, useNavigate, useParams } from "react-router-dom";
import { AddTrackPicker } from "../components/AddTrackPicker";
import { DrillCard } from "../components/DrillCard";
import { DrillFilterBar } from "../components/DrillFilterBar";
import { DrillFormModal } from "../components/DrillFormModal";
import { DrillInfoModal } from "../components/DrillInfoModal";
import {
  ChevronDownIcon,
  ChevronUpIcon,
  CheckIcon,
  ClipboardListIcon,
  ClockIcon,
  InfoIcon,
  PencilIcon,
  StarIcon,
  TrashIcon,
  XIcon,
} from "../components/icons";
import { useToast } from "../components/ToastProvider";
import * as db from "../storage/db";
import { categorySlug } from "../utils/categorySlug";
import type {
  Drill,
  DrillCategory,
  DrillDifficulty,
  DrillInput,
  DrillSegment,
  PlanSegment,
} from "../types";
import { filterDrills } from "../utils/filterDrills";
import { computeSchedule, formatClock, parseTimeToMinutes } from "../utils/schedule";
import { toggleInSet } from "../utils/toggleSet";

interface AutoGeneratedNavState {
  segments?: PlanSegment[];
  autoGenerated?: boolean;
}

export function PlanBuilder() {
  const { id } = useParams();
  const navigate = useNavigate();
  const location = useLocation();
  const showToast = useToast();
  const isNew = !id || id === "new";
  const [navState] = useState<AutoGeneratedNavState | null>(
    () => (location.state as AutoGeneratedNavState | null) ?? null
  );

  const [allDrills, setAllDrills] = useState<Drill[]>([]);
  const drillsById = useMemo(() => {
    const map = new Map<string, Drill>();
    allDrills.forEach((d) => map.set(d.id, d));
    return map;
  }, [allDrills]);

  const [existingId, setExistingId] = useState<string | undefined>(undefined);
  const [loadingPlan, setLoadingPlan] = useState(!isNew);
  const [notFound, setNotFound] = useState(false);

  const [name, setName] = useState("");
  const [startTime, setStartTime] = useState("");
  const [endTime, setEndTime] = useState("");
  const [favorite, setFavorite] = useState(false);
  const [segments, setSegments] = useState<PlanSegment[]>(navState?.segments ?? []);
  const [error, setError] = useState("");
  const [branchTargetId, setBranchTargetId] = useState<string | null>(null);
  const [infoDrill, setInfoDrill] = useState<Drill | null>(null);
  const [drawerOpen, setDrawerOpen] = useState(false);
  const [showCreateDrillForm, setShowCreateDrillForm] = useState(false);
  const [editingDurationId, setEditingDurationId] = useState<string | null>(null);
  const [durationDraft, setDurationDraft] = useState("");

  const [query, setQuery] = useState("");
  const [categories, setCategories] = useState<Set<DrillCategory>>(new Set());
  const [difficulties, setDifficulties] = useState<Set<DrillDifficulty>>(new Set());
  const [minRating, setMinRating] = useState(0);

  useEffect(() => {
    if (navState?.autoGenerated) {
      showToast("Practice plan auto-generated — review and save when ready");
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  useEffect(() => {
    let active = true;
    db.getDrills().then((drills) => {
      if (active) setAllDrills(drills);
    });
    return () => {
      active = false;
    };
  }, []);

  useEffect(() => {
    if (isNew) return;
    let active = true;
    db.getPlan(id!).then((plan) => {
      if (!active) return;
      if (!plan) {
        setNotFound(true);
        setLoadingPlan(false);
        return;
      }
      setExistingId(plan.id);
      setName(plan.name);
      setStartTime(plan.startTime ?? "");
      setEndTime(plan.endTime ?? "");
      setFavorite(plan.favorite);
      setSegments(plan.segments);
      setLoadingPlan(false);
    });
    return () => {
      active = false;
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [id, isNew]);

  const filtered = useMemo(
    () => filterDrills(allDrills, query, categories, difficulties, minRating),
    [allDrills, query, categories, difficulties, minRating]
  );

  const schedule = useMemo(
    () => computeSchedule(segments, startTime || undefined, endTime || undefined),
    [segments, startTime, endTime]
  );

  const usedDrillIds = useMemo(() => {
    const ids = new Set<string>();
    segments.forEach((seg) => {
      if (seg.kind === "drill") seg.tracks.forEach((t) => ids.add(t.drillId));
    });
    return ids;
  }, [segments]);

  const categoryBreakdown = useMemo(() => {
    const totals = new Map<DrillCategory, number>();
    segments.forEach((seg) => {
      if (seg.kind !== "drill") return;
      seg.tracks.forEach((t) => {
        const drill = drillsById.get(t.drillId);
        if (!drill) return;
        totals.set(drill.category, (totals.get(drill.category) ?? 0) + t.duration);
      });
    });
    return [...totals.entries()].sort((a, b) => b[1] - a[1]);
  }, [segments, drillsById]);
  const maxCategoryMinutes = Math.max(1, ...categoryBreakdown.map(([, minutes]) => minutes));

  if (!isNew && loadingPlan) {
    return (
      <div className="page">
        <p className="empty-state">Loading practice plan…</p>
      </div>
    );
  }

  if (!isNew && notFound) {
    return (
      <div className="page">
        <p className="empty-state">That practice plan could not be found.</p>
        <button type="button" className="btn" onClick={() => navigate("/plans")}>
          Back to plans
        </button>
      </div>
    );
  }

  async function handleCreateDrill(input: DrillInput) {
    const created = await db.addDrill(input);
    setAllDrills(await db.getDrills());
    addBlock(created);
    setShowCreateDrillForm(false);
    showToast(`"${created.name}" added to your library and this plan`);
  }

  function addBlock(drill: Drill) {
    setSegments((prev) => [
      ...prev,
      {
        segmentId: db.makeId(),
        kind: "drill",
        tracks: [
          {
            trackId: db.makeId(),
            label: "Court 1",
            drillId: drill.id,
            duration: drill.duration,
            notes: "",
          },
        ],
      },
    ]);
  }

  function addBreakAt(index: number) {
    setSegments((prev) => {
      const next = [...prev];
      next.splice(index, 0, { segmentId: db.makeId(), kind: "break", label: "Break", duration: 5 });
      return next;
    });
  }

  function updateBreak(segmentId: string, changes: Partial<{ label: string; duration: number }>) {
    setSegments((prev) =>
      prev.map((seg) => (seg.kind === "break" && seg.segmentId === segmentId ? { ...seg, ...changes } : seg))
    );
  }

  function addTrackToSegment(segmentId: string, drill: Drill) {
    setSegments((prev) =>
      prev.map((seg) =>
        seg.kind === "drill" && seg.segmentId === segmentId
          ? {
              ...seg,
              tracks: [
                ...seg.tracks,
                {
                  trackId: db.makeId(),
                  label: `Court ${seg.tracks.length + 1}`,
                  drillId: drill.id,
                  duration: drill.duration,
                  notes: "",
                },
              ],
            }
          : seg
      )
    );
    setBranchTargetId(null);
  }

  function removeTrack(segmentId: string, trackId: string) {
    setSegments((prev) =>
      prev
        .map((seg) =>
          seg.kind === "drill" && seg.segmentId === segmentId
            ? { ...seg, tracks: seg.tracks.filter((t) => t.trackId !== trackId) }
            : seg
        )
        .filter((seg) => seg.kind === "break" || seg.tracks.length > 0)
    );
  }

  function removeSegment(segmentId: string) {
    setSegments((prev) => prev.filter((seg) => seg.segmentId !== segmentId));
  }

  function moveSegment(index: number, direction: -1 | 1) {
    setSegments((prev) => {
      const next = [...prev];
      const target = index + direction;
      if (target < 0 || target >= next.length) return prev;
      [next[index], next[target]] = [next[target], next[index]];
      return next;
    });
  }

  function updateTrack(
    segmentId: string,
    trackId: string,
    changes: Partial<{ duration: number; notes: string; label: string }>
  ) {
    setSegments((prev) =>
      prev.map((seg) =>
        seg.kind === "drill" && seg.segmentId === segmentId
          ? {
              ...seg,
              tracks: seg.tracks.map((t) =>
                t.trackId === trackId ? { ...t, ...changes } : t
              ),
            }
          : seg
      )
    );
  }

  function segmentTitle(segment: DrillSegment): string {
    return segment.tracks
      .map((t) => drillsById.get(t.drillId)?.name ?? "Removed drill")
      .join(" + ");
  }

  function primaryDrillOf(segment: DrillSegment): Drill | undefined {
    return drillsById.get(segment.tracks[0].drillId);
  }

  function updateSegmentDuration(segmentId: string, minutes: number) {
    setSegments((prev) =>
      prev.map((seg) => {
        if (seg.segmentId !== segmentId) return seg;
        return seg.kind === "break"
          ? { ...seg, duration: minutes }
          : { ...seg, tracks: seg.tracks.map((t) => ({ ...t, duration: minutes })) };
      })
    );
  }

  function startEditingDuration(segmentId: string, currentDuration: number) {
    setEditingDurationId(segmentId);
    setDurationDraft(String(currentDuration));
  }

  function commitDurationDraft(segmentId: string) {
    updateSegmentDuration(segmentId, Math.max(1, Number(durationDraft) || 1));
    setEditingDurationId(null);
  }

  async function handleSave() {
    if (!name.trim()) {
      setError("Give your practice plan a name.");
      return;
    }
    const input = {
      name: name.trim(),
      startTime: startTime || undefined,
      endTime: endTime || undefined,
      segments,
      favorite,
    };
    if (existingId) {
      await db.updatePlan(existingId, input);
      showToast("Practice plan saved");
      navigate("/plans");
    } else {
      const created = await db.addPlan(input);
      showToast("Practice plan saved");
      navigate(`/plans/${created.id}`);
    }
  }

  return (
    <div className="page">
      <div className="page-header">
        <h1>{existingId ? "Edit Practice Plan" : "New Practice Plan"}</h1>
        <div className="page-header-actions">
          <button
            type="button"
            className={favorite ? "btn fav-active icon-label" : "btn fav-star icon-label"}
            onClick={() => setFavorite((f) => !f)}
          >
            <StarIcon /> {favorite ? "Favorited" : "Favorite"}
          </button>
          <button type="button" className="btn-text" onClick={() => navigate("/plans")}>
            Back to plans
          </button>
        </div>
      </div>

      <div className="plan-builder-grid">
        <section className="plan-builder-main">
          <div className="plan-builder-column-header">
            <h2>Practice schedule</h2>
            <button type="button" className="btn btn-primary" onClick={() => setDrawerOpen(true)}>
              + Add Drills
            </button>
          </div>
          {schedule.scheduled.length === 0 ? (
            <div className="empty-state">
              <ClipboardListIcon size={36} className="empty-state-icon" />
              <p>
                No time blocks yet. Click "+ Add Drills" to open the library and build your first
                block.
              </p>
            </div>
          ) : (
            <ol className="plan-segment-list">
              {schedule.scheduled.map(({ segment, duration, startLabel, endLabel }, index) => {
                const breakInsertSlot = (
                  <li className="break-insert-slot" key={`insert-${segment.segmentId}`}>
                    <button
                      type="button"
                      className="break-insert-btn"
                      onClick={() => addBreakAt(index)}
                    >
                      + Add Break
                    </button>
                  </li>
                );

                if (segment.kind === "break") {
                  return (
                    <Fragment key={segment.segmentId}>
                      {breakInsertSlot}
                      <li className="plan-segment plan-segment-break">
                      <div className="plan-segment-header">
                        <div className="plan-segment-order">
                          <button
                            type="button"
                            className="btn-icon"
                            disabled={index === 0}
                            onClick={() => moveSegment(index, -1)}
                            aria-label="Move block up"
                          >
                            <ChevronUpIcon />
                          </button>
                          <button
                            type="button"
                            className="btn-icon"
                            disabled={index === schedule.scheduled.length - 1}
                            onClick={() => moveSegment(index, 1)}
                            aria-label="Move block down"
                          >
                            <ChevronDownIcon />
                          </button>
                        </div>
                        <div className="plan-segment-time">
                          <input
                            className="break-label-input"
                            value={segment.label}
                            onChange={(e) => updateBreak(segment.segmentId, { label: e.target.value })}
                            placeholder="Break"
                            aria-label="Break label"
                          />
                          <span className="page-subtitle plan-segment-duration">
                            {startLabel && endLabel && (
                              <>
                                <span>
                                  {startLabel} – {endLabel}
                                </span>
                                <span className="duration-separator" aria-hidden="true">
                                  ·
                                </span>
                              </>
                            )}
                            <span className="icon-label">
                              <ClockIcon />
                              {editingDurationId === segment.segmentId ? (
                                <input
                                  type="number"
                                  min={1}
                                  autoFocus
                                  className="segment-duration-input"
                                  value={durationDraft}
                                  onChange={(e) => setDurationDraft(e.target.value)}
                                  onBlur={() => commitDurationDraft(segment.segmentId)}
                                  onKeyDown={(e) => {
                                    if (e.key === "Enter") commitDurationDraft(segment.segmentId);
                                    if (e.key === "Escape") setEditingDurationId(null);
                                  }}
                                />
                              ) : (
                                <>
                                  {`${duration} min`}
                                  <button
                                    type="button"
                                    className="btn-icon-plain"
                                    aria-label="Edit break duration"
                                    onClick={() => startEditingDuration(segment.segmentId, duration)}
                                  >
                                    <PencilIcon />
                                  </button>
                                </>
                              )}
                            </span>
                          </span>
                        </div>
                        <div className="plan-segment-actions">
                          <button
                            type="button"
                            className="btn-icon-danger"
                            onClick={() => removeSegment(segment.segmentId)}
                            aria-label="Remove break"
                            title="Remove break"
                          >
                            <TrashIcon />
                          </button>
                        </div>
                      </div>
                    </li>
                    </Fragment>
                  );
                }

                const primaryDrill = primaryDrillOf(segment);
                return (
                  <Fragment key={segment.segmentId}>
                    {breakInsertSlot}
                    <li className="plan-segment">
                  <div className="plan-segment-header">
                    <div className="plan-segment-order">
                      <button
                        type="button"
                        className="btn-icon"
                        disabled={index === 0}
                        onClick={() => moveSegment(index, -1)}
                        aria-label="Move block up"
                      >
                        <ChevronUpIcon />
                      </button>
                      <button
                        type="button"
                        className="btn-icon"
                        disabled={index === schedule.scheduled.length - 1}
                        onClick={() => moveSegment(index, 1)}
                        aria-label="Move block down"
                      >
                        <ChevronDownIcon />
                      </button>
                    </div>
                    <div className="plan-segment-time">
                      <div className="plan-segment-title-row">
                        {primaryDrill ? (
                          <button
                            type="button"
                            className="plan-segment-title-btn"
                            onClick={() => setInfoDrill(primaryDrill)}
                            aria-label={`View details for ${segmentTitle(segment)}`}
                          >
                            <span className="plan-segment-title-text">
                              {segmentTitle(segment)}
                            </span>
                            <span className="info-icon">
                              <InfoIcon />
                            </span>
                          </button>
                        ) : (
                          <span className="plan-segment-title-text plan-track-drill-missing">
                            {segmentTitle(segment)}
                          </span>
                        )}
                      </div>
                      <span className="page-subtitle plan-segment-duration">
                        {startLabel && endLabel && (
                          <>
                            <span>
                              {startLabel} – {endLabel}
                            </span>
                            <span className="duration-separator" aria-hidden="true">
                              ·
                            </span>
                          </>
                        )}
                        <span className="icon-label">
                          <ClockIcon />
                          {editingDurationId === segment.segmentId ? (
                            <input
                              type="number"
                              min={1}
                              autoFocus
                              className="segment-duration-input"
                              value={durationDraft}
                              onChange={(e) => setDurationDraft(e.target.value)}
                              onBlur={() => commitDurationDraft(segment.segmentId)}
                              onKeyDown={(e) => {
                                if (e.key === "Enter") commitDurationDraft(segment.segmentId);
                                if (e.key === "Escape") setEditingDurationId(null);
                              }}
                            />
                          ) : (
                            <>
                              {`${duration} min`}
                              <button
                                type="button"
                                className="btn-icon-plain"
                                aria-label="Edit block duration"
                                onClick={() => startEditingDuration(segment.segmentId, duration)}
                              >
                                <PencilIcon />
                              </button>
                            </>
                          )}
                        </span>
                      </span>
                    </div>
                    <div className="plan-segment-actions">
                      <button
                        type="button"
                        className="btn btn-sm"
                        onClick={() => setBranchTargetId(segment.segmentId)}
                      >
                        + Add Parallel Court
                      </button>
                      <button
                        type="button"
                        className="btn-icon-danger"
                        onClick={() => removeSegment(segment.segmentId)}
                        aria-label="Remove block"
                        title="Remove block"
                      >
                        <TrashIcon />
                      </button>
                    </div>
                  </div>

                  {primaryDrill && (
                    <div className="badge-group plan-segment-pills">
                      <span className={`badge badge-category-${categorySlug(primaryDrill.category)}`}>
                        {primaryDrill.category}
                      </span>
                      <span
                        className={`badge badge-difficulty badge-${primaryDrill.difficulty.toLowerCase()}`}
                      >
                        {primaryDrill.difficulty}
                      </span>
                    </div>
                  )}

                  <div className="plan-track-grid">
                    {segment.tracks.map((track) => {
                      const drill = drillsById.get(track.drillId);
                      return (
                        <div className="plan-track" key={track.trackId}>
                          {segment.tracks.length > 1 && (
                            <input
                              className="plan-track-label"
                              value={track.label}
                              onChange={(e) =>
                                updateTrack(segment.segmentId, track.trackId, {
                                  label: e.target.value,
                                })
                              }
                              aria-label="Court label"
                            />
                          )}
                          {segment.tracks.length > 1 &&
                            (drill ? (
                              <>
                                <button
                                  type="button"
                                  className="plan-track-drill-name"
                                  onClick={() => setInfoDrill(drill)}
                                >
                                  {drill.name}
                                </button>
                                <div className="badge-group">
                                  <span
                                    className={`badge badge-category-${categorySlug(drill.category)}`}
                                  >
                                    {drill.category}
                                  </span>
                                  <span
                                    className={`badge badge-difficulty badge-${drill.difficulty.toLowerCase()}`}
                                  >
                                    {drill.difficulty}
                                  </span>
                                </div>
                              </>
                            ) : (
                              <span className="plan-track-drill-name plan-track-drill-missing">
                                (drill removed from library)
                              </span>
                            ))}
                          <label className="field">
                            <span>Notes for this session</span>
                            <input
                              value={track.notes ?? ""}
                              onChange={(e) =>
                                updateTrack(segment.segmentId, track.trackId, {
                                  notes: e.target.value,
                                })
                              }
                              placeholder="Coaching cues, variations…"
                            />
                          </label>
                          {segment.tracks.length > 1 && (
                            <button
                              type="button"
                              className="btn btn-danger btn-sm"
                              onClick={() => removeTrack(segment.segmentId, track.trackId)}
                            >
                              Remove
                            </button>
                          )}
                        </div>
                      );
                    })}
                  </div>
                    </li>
                  </Fragment>
                );
              })}
              <li className="break-insert-slot">
                <button
                  type="button"
                  className="break-insert-btn"
                  onClick={() => addBreakAt(segments.length)}
                >
                  + Add Break
                </button>
              </li>
            </ol>
          )}
        </section>

        <aside className="plan-builder-sidebar">
          <div className="sidebar-card">
            {error && <div className="form-error">{error}</div>}
            <div className="form">
              <label className="field">
                <span>Plan name</span>
                <input
                  value={name}
                  onChange={(e) => setName(e.target.value)}
                  placeholder="e.g. Tuesday Serve & Pass Focus"
                />
              </label>
              <div className="field-row">
                <label className="field">
                  <span>Start time</span>
                  <input
                    type="time"
                    value={startTime}
                    onChange={(e) => setStartTime(e.target.value)}
                  />
                </label>
                <label className="field">
                  <span>End time</span>
                  <input type="time" value={endTime} onChange={(e) => setEndTime(e.target.value)} />
                </label>
              </div>
            </div>
          </div>

          <div className="sidebar-card">
            <h2>Plan Stats</h2>
            <dl className="stat-row-list">
              {schedule.windowMinutes !== undefined && (
                <div className="stat-row">
                  <dt>Practice window</dt>
                  <dd>
                    {formatClock(parseTimeToMinutes(startTime)!)} –{" "}
                    {formatClock(parseTimeToMinutes(endTime)!)} ({schedule.windowMinutes} min)
                  </dd>
                </div>
              )}
              <div className="stat-row">
                <dt>Time planned</dt>
                <dd>{schedule.totalMinutes} min</dd>
              </div>
              <div className="stat-row">
                <dt>Time left</dt>
                <dd
                  className={
                    schedule.remainingMinutes !== undefined && schedule.remainingMinutes < 0
                      ? "stat-value-over"
                      : schedule.remainingMinutes === 0
                        ? "stat-value-exact"
                        : undefined
                  }
                >
                  {schedule.remainingMinutes === undefined ? (
                    "Set start/end time to track"
                  ) : schedule.remainingMinutes > 0 ? (
                    `${schedule.remainingMinutes} min unscheduled`
                  ) : schedule.remainingMinutes === 0 ? (
                    <span className="icon-label">
                      Fully scheduled <CheckIcon />
                    </span>
                  ) : (
                    `${-schedule.remainingMinutes} min over`
                  )}
                </dd>
              </div>
            </dl>

            {categoryBreakdown.length > 0 && (
              <div className="stat-bars">
                <span className="filter-group-label">Time by skill</span>
                {categoryBreakdown.map(([category, minutes]) => (
                  <div className="stat-bar-row" key={category}>
                    <span className="stat-bar-label">{category}</span>
                    <span className="stat-bar-track">
                      <span
                        className="stat-bar-fill"
                        style={{ width: `${(minutes / maxCategoryMinutes) * 100}%` }}
                      />
                    </span>
                    <span className="stat-bar-value">{minutes} min</span>
                  </div>
                ))}
              </div>
            )}
          </div>

          <button type="button" className="btn btn-primary btn-block" onClick={handleSave}>
            Save Practice Plan
          </button>
        </aside>
      </div>

      {drawerOpen && (
        <div className="drawer-overlay" onClick={() => setDrawerOpen(false)}>
          <aside className="drill-drawer" onClick={(e) => e.stopPropagation()}>
            <div className="drill-drawer-header">
              <h2>Add drills from library</h2>
              <button
                type="button"
                className="btn-icon"
                onClick={() => setDrawerOpen(false)}
                aria-label="Close"
              >
                <XIcon />
              </button>
            </div>
            <div className="drill-drawer-body">
              <DrillFilterBar
                query={query}
                onQueryChange={setQuery}
                categories={categories}
                onToggleCategory={(c) => setCategories((prev) => toggleInSet(prev, c))}
                onClearCategories={() => setCategories(new Set())}
                difficulties={difficulties}
                onToggleDifficulty={(d) => setDifficulties((prev) => toggleInSet(prev, d))}
                onClearDifficulties={() => setDifficulties(new Set())}
                minRating={minRating}
                onMinRatingChange={setMinRating}
              />
              <button
                type="button"
                className="create-drill-card"
                onClick={() => setShowCreateDrillForm(true)}
              >
                + Create New Drill
              </button>
              <div className="drill-grid">
                {filtered.map((drill) => (
                  <DrillCard
                    key={drill.id}
                    drill={drill}
                    added={usedDrillIds.has(drill.id)}
                    onClick={() => addBlock(drill)}
                    action={{
                      label: usedDrillIds.has(drill.id) ? "Add Again" : "Add to Plan",
                      onClick: addBlock,
                    }}
                  />
                ))}
              </div>
            </div>
          </aside>
        </div>
      )}

      {branchTargetId && (
        <AddTrackPicker
          drills={allDrills}
          onPick={(drill) => addTrackToSegment(branchTargetId, drill)}
          onClose={() => setBranchTargetId(null)}
        />
      )}

      {infoDrill && <DrillInfoModal drill={infoDrill} onClose={() => setInfoDrill(null)} />}

      {showCreateDrillForm && (
        <DrillFormModal onSave={handleCreateDrill} onClose={() => setShowCreateDrillForm(false)} />
      )}
    </div>
  );
}
